using System.Collections.Generic;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;

/// <summary>
/// Furnishes EVERY non-stair room of the School Of The Dead map with simple,
/// type-appropriate props so the level reads as a believable (but dark and
/// abandoned) school instead of empty boxes.
///
/// HOW IT WORKS
/// ------------
/// The whole map sits under a root ("School Map - Zombies Scale") scaled to 0.4,
/// so local positions are meaningless. This tool therefore works ENTIRELY in
/// WORLD space:
///   * A room is located/sized by its "&lt;roomid&gt;_Floor" MeshRenderer world
///     bounds. The floor-top Y (bounds.max.y) is where every prop's base sits.
///   * Doorways are kept clear using the world positions of the room's own
///     transoms ("&lt;roomid&gt;_&lt;N|S|E|W&gt;_Seg#_..._Transom", ignoring the
///     "AntiZFightCover" variants).
///
/// Props are crude primitive constructions (cubes mostly) on dark, grimy
/// materials - this tool owns LAYOUT/STRUCTURE, not final art.
///
/// RE-RUNNABLE &amp; NON-DESTRUCTIVE
/// ----------------------------
/// Everything is created under a single root "Generated_RoomProps" that is
/// destroyed and rebuilt each run. The tool never edits, moves, or deletes any
/// existing scene object; it only creates props (and "Furniture - *" materials).
/// Layout is deterministic (RNG seeded from the room id) so re-runs reproduce
/// the same arrangement.
/// </summary>
public static class SchoolRoomFurnisher
{
    private const string ScenePath = "Assets/Scenes/SchoolOfTheDead.unity";
    private const string MaterialFolder = "Assets/Materials/SchoolOfTheDead";
    private const string RootName = "Generated_RoomProps";

    // World-space margins / clearances.
    private const float WallInset = 0.8f;       // keep props ~0.8m off the walls
    private const float DoorClearRadius = 1.8f; // keep a clear bubble at each doorway

    // Roughly one prop per this many square metres of floor (rooms are capped per type too).
    private const float SqMetresPerProp = 7f;

    // Roots that are generated by this or other tools - never treat as rooms / scan for floors.
    private static readonly string[] GeneratedRootNames =
    {
        "Generated_RoomProps",
        "Generated_Props",
        "Generated_Doors",
        "Generated_Geometry_Fixes",
        "Generated_SecretEgg",
        "Generated_Perks",
    };

    private enum RoomType
    {
        Classroom,
        ScienceLab,
        Conference,
        Cafeteria,
        Kitchen,
        Library,
        Gym,
        Office,
        Security,
        Nurse,
        Storage,
        Janitor,
        Utility,
        Courtyard,
    }

    // Authoritative room -> type table (stairs / parking_lot deliberately excluded).
    private static readonly (string id, RoomType type)[] Rooms =
    {
        // CLASSROOMS
        ("math_room", RoomType.Classroom),
        ("music_room", RoomType.Classroom),
        ("history_room", RoomType.Classroom),
        ("east_room_1", RoomType.Classroom),
        ("east_room_2", RoomType.Classroom),
        ("east_room_3", RoomType.Classroom),
        ("south_office_classroom_1", RoomType.Classroom),
        ("south_office_classroom_2", RoomType.Classroom),
        ("south_office_classroom_3", RoomType.Classroom),
        ("south_office_classroom_4", RoomType.Classroom),
        ("west_cafeteria_classroom_1", RoomType.Classroom),
        ("west_classroom_1", RoomType.Classroom),
        ("west_classroom_2", RoomType.Classroom),
        ("starter", RoomType.Classroom),

        // SCIENCE LAB
        ("science_lab", RoomType.ScienceLab),

        // CONFERENCE
        ("conference_room", RoomType.Conference),

        // CAFETERIA + KITCHEN
        ("cafeteria", RoomType.Cafeteria),
        ("cafeteria_kitchen", RoomType.Kitchen),

        // LIBRARY
        ("library", RoomType.Library),
        ("library_basement", RoomType.Library),
        ("library_basement_annex", RoomType.Library),

        // GYM
        ("gym", RoomType.Gym),

        // OFFICES
        ("main_office", RoomType.Office),
        ("principal_office", RoomType.Office),
        ("west_south_office", RoomType.Office),

        // SECURITY
        ("security_room", RoomType.Security),

        // NURSE
        ("nurses_office", RoomType.Nurse),
        ("nurses_office_backroom", RoomType.Nurse),

        // STORAGE / JANITOR
        ("west_wing_storage", RoomType.Storage),
        ("janitors_closet", RoomType.Janitor),
        ("janitors_closet_2", RoomType.Janitor),

        // UTILITY / BASEMENT / TELEPORTER
        ("teleporter_room", RoomType.Utility),
        ("the_vault", RoomType.Utility),
        ("underground_tunnel", RoomType.Utility),

        // COURTYARDS (outdoor - keep light). courtyard_fountain has no _Floor; it
        // is listed so the run logs it as skipped rather than silently ignoring it.
        ("courtyard", RoomType.Courtyard),
        ("courtyard_east", RoomType.Courtyard),
        ("courtyard_west", RoomType.Courtyard),
        ("courtyard_fountain", RoomType.Courtyard),
    };

    // --- Shared materials (created once per run) ----------------------------
    private static Material _matWoodDark;
    private static Material _matWoodMid;
    private static Material _matMetalGrey;
    private static Material _matMetalDark;
    private static Material _matWhiteboard;
    private static Material _matFabricDark;
    private static Material _matPlasticDark;
    private static Material _matConcrete;
    private static Material _matRust;
    private static Material _matGlassDark;

    [MenuItem("Tools/School Of The Dead/Furnish Rooms")]
    public static void FurnishRooms()
    {
        EnsureFolder("Assets/Materials");
        EnsureFolder(MaterialFolder);
        BuildMaterials();

        Scene scene = EditorSceneManager.OpenScene(ScenePath, OpenSceneMode.Single);

        // Re-runnable: destroy + recreate our single root at world origin, scale 1.
        GameObject root = RecreateRoot();

        // Gather every relevant renderer once (skipping generated roots), keyed by name.
        // We need exact "<roomid>_Floor" lookups and per-room transom collections.
        List<MeshRenderer> allRenderers = new List<MeshRenderer>();
        foreach (GameObject rootGo in scene.GetRootGameObjects())
        {
            if (IsGeneratedRoot(rootGo.name))
            {
                continue;
            }

            allRenderers.AddRange(rootGo.GetComponentsInChildren<MeshRenderer>(true));
        }

        int roomsFurnished = 0;
        int totalProps = 0;
        List<string> skipped = new List<string>();

        foreach ((string id, RoomType type) in Rooms)
        {
            MeshRenderer floor = FindFloor(allRenderers, id);
            if (floor == null)
            {
                skipped.Add($"{id} (no '{id}_Floor' in scene)");
                continue;
            }

            List<Vector3> doorways = CollectDoorways(allRenderers, id);

            // Per-room container for tidiness.
            GameObject roomGo = new GameObject(id);
            roomGo.transform.SetParent(root.transform, false);

            RoomContext ctx = new RoomContext(id, type, floor.bounds, doorways, roomGo.transform);

            int before = ctx.PropCount;
            Dispatch(ctx);
            int placed = ctx.PropCount - before;
            totalProps += placed;

            if (placed > 0)
            {
                roomsFurnished++;
            }
            else
            {
                // Room was found but nothing fit (too small / fully blocked). Keep the
                // empty container - harmless - but note it.
                skipped.Add($"{id} (found but no props fit)");
            }
        }

        EditorSceneManager.MarkSceneDirty(scene);
        EditorSceneManager.SaveScene(scene);
        AssetDatabase.SaveAssets();
        AssetDatabase.Refresh();

        string skipMsg = skipped.Count == 0 ? "none" : string.Join(", ", skipped);
        Debug.Log(
            $"[SchoolRoomFurnisher] Furnished {roomsFurnished} room(s) with {totalProps} prop(s) " +
            $"under '{RootName}'. Skipped: {skipMsg}. " +
            "Re-running rebuilds Generated_RoomProps from scratch (non-destructive).");
    }

    // === Per-room context ===================================================

    /// <summary>
    /// Everything a furnish method needs about one room, plus prop counting and
    /// the shared placement-validity test (inside footprint + clear of doorways).
    /// </summary>
    private sealed class RoomContext
    {
        public readonly string Id;
        public readonly RoomType Type;
        public readonly Bounds Floor;     // world bounds of the floor renderer
        public readonly float FloorY;     // world Y of the floor TOP (props sit here)
        public readonly List<Vector3> Doorways;
        public readonly Transform Parent; // per-room container
        public readonly System.Random Rng;

        // Inner (walkable / placeable) rectangle in world X/Z, shrunk by WallInset.
        public readonly float MinX, MaxX, MinZ, MaxZ;
        public readonly float SizeX, SizeZ, Area;

        public int PropCount { get; private set; }

        /// <summary>Room centre in world space, at the floor-top Y.</summary>
        public Vector3 Center => new Vector3(Floor.center.x, FloorY, Floor.center.z);

        public RoomContext(string id, RoomType type, Bounds floor, List<Vector3> doorways, Transform parent)
        {
            Id = id;
            Type = type;
            Floor = floor;
            FloorY = floor.max.y;
            Doorways = doorways;
            Parent = parent;
            Rng = new System.Random(StableHash(id));

            MinX = floor.min.x + WallInset;
            MaxX = floor.max.x - WallInset;
            MinZ = floor.min.z + WallInset;
            MaxZ = floor.max.z - WallInset;
            SizeX = Mathf.Max(0f, MaxX - MinX);
            SizeZ = Mathf.Max(0f, MaxZ - MinZ);
            Area = floor.size.x * floor.size.z;
        }

        public int PropBudget()
        {
            return Mathf.Max(1, Mathf.RoundToInt(Area / SqMetresPerProp));
        }

        public void Count() => PropCount++;

        /// <summary>
        /// True if an axis-aligned prop footprint (centred at world x/z, with the
        /// given half extents along X/Z after yaw is applied by the caller) fits
        /// inside the inset room rectangle and clears every doorway bubble.
        /// </summary>
        public bool Fits(float x, float z, float halfX, float halfZ)
        {
            if (x - halfX < MinX || x + halfX > MaxX) return false;
            if (z - halfZ < MinZ || z + halfZ > MaxZ) return false;

            float clearR = DoorClearRadius + Mathf.Max(halfX, halfZ);
            float clearSq = clearR * clearR;
            foreach (Vector3 d in Doorways)
            {
                float dx = d.x - x;
                float dz = d.z - z;
                if (dx * dx + dz * dz < clearSq) return false;
            }

            return true;
        }
    }

    private static void Dispatch(RoomContext ctx)
    {
        switch (ctx.Type)
        {
            case RoomType.Classroom: FurnishClassroom(ctx); break;
            case RoomType.ScienceLab: FurnishLab(ctx); break;
            case RoomType.Conference: FurnishConference(ctx); break;
            case RoomType.Cafeteria: FurnishCafeteria(ctx); break;
            case RoomType.Kitchen: FurnishKitchen(ctx); break;
            case RoomType.Library: FurnishLibrary(ctx); break;
            case RoomType.Gym: FurnishGym(ctx); break;
            case RoomType.Office: FurnishOffice(ctx); break;
            case RoomType.Security: FurnishSecurity(ctx); break;
            case RoomType.Nurse: FurnishNurse(ctx); break;
            case RoomType.Storage: FurnishStorage(ctx, janitor: false); break;
            case RoomType.Janitor: FurnishStorage(ctx, janitor: true); break;
            case RoomType.Utility: FurnishUtility(ctx); break;
            case RoomType.Courtyard: FurnishCourtyard(ctx); break;
        }
    }

    // === Per-type furnish methods ==========================================

    private static void FurnishClassroom(RoomContext ctx)
    {
        // Choose the "front" (board) wall deterministically: the wall farthest from
        // any doorway so desks never face a door. Everything below is oriented from
        // that wall's geometry, so the whole room reads consistently regardless of
        // which way the room happens to be aligned in world space.
        Wall front = ChooseFrontWall(ctx);
        WallInfo(ctx, front, out float ffx, out float ffz, out bool runAlongX, out _);

        // Axis abstraction. "depth" = perpendicular to the board (back wall -> front
        // wall); "run" = along the board (where columns of desks spread out).
        bool depthIsZ = runAlongX;                 // N/S front -> depth on Z; E/W front -> depth on X
        float frontCoord = depthIsZ ? ffz : ffx;   // world coord of the front wall on the depth axis
        float backCoord = depthIsZ
            ? (front == Wall.North ? ctx.MinZ : ctx.MaxZ)
            : (front == Wall.East ? ctx.MinX : ctx.MaxX);
        float depthSign = Mathf.Sign(frontCoord - backCoord);   // back -> front along depth
        float runMin = runAlongX ? ctx.MinX : ctx.MinZ;
        float runMax = runAlongX ? ctx.MaxX : ctx.MaxZ;
        float runCenter = 0.5f * (runMin + runMax);

        Vector3 inward = InwardNormal(front);       // board -> students
        Vector3 boardDir = -inward;                 // students -> board (what a student faces)
        float studentYaw = YawFromDir(boardDir);    // every student desk + chair uses this
        float teacherYaw = YawFromDir(inward);      // teacher faces the students

        // 1) Whiteboard on the chosen front wall (decorative, no collider).
        MakeWhiteboard(ctx, front, "Whiteboard");

        // 2) Teacher desk near the front wall, facing the students; chair tucked
        //    between the desk and the wall (occupant on the wall side).
        float teacherDepth = frontCoord - depthSign * 0.6f; // 0.6m off the board wall
        float tdx = depthIsZ ? runCenter : teacherDepth;
        float tdz = depthIsZ ? teacherDepth : runCenter;
        if (PlaceAt(ctx, tdx, tdz, 0.6f, 0.45f, p => MakeDesk(ctx, p, teacherYaw, "TeacherDesk")))
        {
            Vector3 tc = new Vector3(tdx, ctx.FloorY, tdz) + (-boardDir) * 0.7f; // wall side of desk
            if (ctx.Fits(tc.x, tc.z, 0.3f, 0.3f)) MakeChair(ctx, tc, teacherYaw, "TeacherChair");
        }

        // 3) Corner shelf + trash can (away from the board wall so they don't crowd it).
        PlaceInCorner(ctx, 0, 1.0f, 0.4f, (pos, yaw) => MakeShelf(ctx, pos, yaw, "Shelf"));
        PlaceInCorner(ctx, 2, 0.3f, 0.3f, (pos, yaw) => MakeTrashCan(ctx, pos, "TrashCan"));

        // 4) Neat rows of student desks, all FACING THE BOARD, chairs tucked behind
        //    each desk, with a clear central aisle running front-to-back so students
        //    (and zombies) can walk up the middle.
        int budget = Mathf.Min(ctx.PropBudget(), 16);
        const float deskW = 1.0f, deskD = 0.6f, runGap = 0.7f, depthGap = 1.15f, aisleHalf = 0.7f;

        // Rows march from near the back wall toward the front, stopping short of the
        // teacher desk. "d" is the world coord on the depth axis for the row.
        // (Guard against a degenerate room so the depth loop always terminates.)
        if (Mathf.Abs(depthSign) < 0.5f) return;
        float firstRow = backCoord + depthSign * 1.2f;
        float lastRow = teacherDepth - depthSign * 1.7f; // gap in front of the teacher
        int row = 0;
        for (float d = firstRow;
             depthSign > 0 ? d <= lastRow : d >= lastRow;
             d += depthSign * depthGap, row++)
        {
            if (ctx.PropCount >= budget) break;
            int col = 0;
            for (float r = runMin + deskW * 0.5f; r + deskW * 0.5f <= runMax && ctx.PropCount < budget; r += deskW + runGap, col++)
            {
                // Keep a clear central aisle (skip desks straddling the run centre).
                if (Mathf.Abs(r - runCenter) < aisleHalf) continue;

                float dx = depthIsZ ? r : d;
                float dz = depthIsZ ? d : r;
                // Footprint half-extents follow the desk's facing: width spans the run
                // axis, depth spans the depth axis.
                float hX = depthIsZ ? deskW * 0.5f + 0.05f : deskD * 0.5f + 0.05f;
                float hZ = depthIsZ ? deskD * 0.5f + 0.05f : deskW * 0.5f + 0.05f;
                int rr = row, cc = col;
                if (PlaceAt(ctx, dx, dz, hX, hZ, p => MakeDesk(ctx, p, studentYaw, $"Desk_{rr}_{cc}")))
                {
                    // Chair tucked behind the desk (away from the board) facing it.
                    Vector3 cp = new Vector3(dx, ctx.FloorY, dz) + (-boardDir) * 0.55f;
                    if (ctx.Fits(cp.x, cp.z, 0.28f, 0.28f)) MakeChair(ctx, cp, studentYaw, $"Chair_{rr}_{cc}");
                }
            }
        }
    }

    private static void FurnishLab(RoomContext ctx)
    {
        // Whiteboard + a sink counter run along the front wall.
        MakeWhiteboard(ctx, Wall.North, "Whiteboard");
        MakeCounterRun(ctx, Wall.North, "SinkCounter", withSink: true);

        // Wall cabinets along a side wall.
        MakeCounterRun(ctx, Wall.West, "WallCabinets", withSink: false);

        // Equipment shelves in a corner.
        PlaceInCorner(ctx, 1, 1.2f, 0.4f, (pos, yaw) => MakeShelf(ctx, pos, yaw, "EquipShelf"));

        // Lab benches with stools down the middle (two rows, wide aisle).
        int budget = Mathf.Min(ctx.PropBudget(), 8);
        const float benchW = 2.2f, benchD = 0.8f, gapZ = 2.0f;
        float[] lanes = { ctx.Center.x - ctx.SizeX * 0.22f, ctx.Center.x + ctx.SizeX * 0.22f };
        int idx = 0;
        for (float z = ctx.MinZ + 1.4f; z <= ctx.MaxZ - 2.0f && ctx.PropCount < budget; z += gapZ)
        {
            foreach (float laneX in lanes)
            {
                if (ctx.PropCount >= budget) break;
                if (PlaceAt(ctx, laneX, z, benchW * 0.5f + 0.05f, benchD * 0.5f + 0.05f,
                        p => MakeTable(ctx, p, 0f, benchW, benchD, 0.9f, _matMetalGrey, $"LabBench_{idx}")))
                {
                    // A stool on each long side.
                    Vector3 s1 = new Vector3(laneX, ctx.FloorY, z + benchD * 0.5f + 0.35f);
                    Vector3 s2 = new Vector3(laneX, ctx.FloorY, z - benchD * 0.5f - 0.35f);
                    if (ctx.Fits(s1.x, s1.z, 0.25f, 0.25f)) MakeStool(ctx, s1, $"Stool_{idx}a");
                    if (ctx.Fits(s2.x, s2.z, 0.25f, 0.25f)) MakeStool(ctx, s2, $"Stool_{idx}b");
                    idx++;
                }
            }
        }
    }

    private static void FurnishConference(RoomContext ctx)
    {
        // One long central table with chairs around it; a cabinet against a wall.
        float tableLen = Mathf.Clamp(ctx.SizeZ * 0.6f, 2.5f, 6f);
        float tableW = Mathf.Clamp(ctx.SizeX * 0.35f, 1.0f, 1.8f);
        Vector3 c = new Vector3(ctx.Center.x, ctx.FloorY, ctx.Center.z);

        if (PlaceAt(ctx, c.x, c.z, tableW * 0.5f + 0.1f, tableLen * 0.5f + 0.1f,
                p => MakeTable(ctx, p, 0f, tableW, tableLen, 0.75f, _matWoodMid, "ConferenceTable")))
        {
            // Chairs down both long sides.
            int perSide = Mathf.Max(2, Mathf.FloorToInt(tableLen / 1.0f));
            for (int i = 0; i < perSide; i++)
            {
                float z = Mathf.Lerp(c.z - tableLen * 0.5f + 0.5f, c.z + tableLen * 0.5f - 0.5f, perSide == 1 ? 0.5f : i / (float)(perSide - 1));
                Vector3 left = new Vector3(c.x - tableW * 0.5f - 0.4f, ctx.FloorY, z);
                Vector3 right = new Vector3(c.x + tableW * 0.5f + 0.4f, ctx.FloorY, z);
                if (ctx.Fits(left.x, left.z, 0.28f, 0.28f)) MakeChair(ctx, left, 90f, $"Chair_L{i}");
                if (ctx.Fits(right.x, right.z, 0.28f, 0.28f)) MakeChair(ctx, right, 270f, $"Chair_R{i}");
            }
        }

        PlaceInCorner(ctx, 0, 1.2f, 0.45f, (pos, yaw) => MakeCabinet(ctx, pos, yaw, "Cabinet"));
    }

    private static void FurnishCafeteria(RoomContext ctx)
    {
        // Food-service line set ~1.2m OFF the north wall so the player can walk
        // behind it (server side). Stop the dining rows short of it.
        const float counterOffset = 1.2f, counterDepth = 0.6f;
        MakeCounterRun(ctx, Wall.North, "FoodCounter", withSink: false, wallOffset: counterOffset);
        float counterFrontZ = ctx.MaxZ - (counterOffset + counterDepth); // inner face of the line

        // Several long tables with bench seats, in neat parallel rows with walking
        // gaps; kept clear of the service line and doorways (Fits handles doors).
        int budget = Mathf.Min(ctx.PropBudget(), 12);
        float tableLen = Mathf.Clamp(ctx.SizeX * 0.5f, 2.5f, 5f);
        const float tableW = 0.9f, rowGap = 2.2f;
        int idx = 0;
        float diningMaxZ = Mathf.Min(ctx.MaxZ - 2.4f, counterFrontZ - 1.0f);
        for (float z = ctx.MinZ + 1.4f; z <= diningMaxZ && ctx.PropCount < budget; z += rowGap)
        {
            float x = ctx.Center.x;
            if (PlaceAt(ctx, x, z, tableLen * 0.5f + 0.1f, tableW * 0.5f + 0.45f,
                    p => MakeTable(ctx, p, 90f, tableW, tableLen, 0.75f, _matWoodMid, $"CafeTable_{idx}")))
            {
                // A bench on each long side. The table runs along world X (it was
                // yawed 90), so benches run along world X too -> bench yaw 0.
                Vector3 b1 = new Vector3(x, ctx.FloorY, z + tableW * 0.5f + 0.32f);
                Vector3 b2 = new Vector3(x, ctx.FloorY, z - tableW * 0.5f - 0.32f);
                if (ctx.Fits(b1.x, b1.z, tableLen * 0.45f, 0.18f)) MakeBench(ctx, b1, 0f, tableLen * 0.9f, $"Bench_{idx}a");
                if (ctx.Fits(b2.x, b2.z, tableLen * 0.45f, 0.18f)) MakeBench(ctx, b2, 0f, tableLen * 0.9f, $"Bench_{idx}b");
                idx++;
            }
        }

        // A trash can + a spilled trays crate near a corner.
        PlaceInCorner(ctx, 2, 0.3f, 0.3f, (pos, yaw) => MakeTrashCan(ctx, pos, "TrashCan"));
        PlaceInCorner(ctx, 3, 0.5f, 0.5f, (pos, yaw) => MakeCrate(ctx, pos, 0.6f, "TrayCrate"));
    }

    private static void FurnishKitchen(RoomContext ctx)
    {
        // Prep/sink line set ~1.2m off the north wall so the player can walk behind
        // it. The south wall keeps a flush back-counter, preserving a clear central
        // working lane (and never blocking the kitchen entrance - Fits clears doors).
        const float counterOffset = 1.2f;
        MakeCounterRun(ctx, Wall.North, "PrepCounterN", withSink: true, wallOffset: counterOffset);
        MakeCounterRun(ctx, Wall.South, "PrepCounterS", withSink: false, wallOffset: 0f);

        // Storage shelves on a side wall.
        MakeWallShelfRun(ctx, Wall.West, "StorageShelves");

        // A prep-table island only when the room is deep enough that the offset
        // north line + island + south counter still leave walking lanes.
        if (ctx.SizeX > 3f && ctx.SizeZ > 5.5f)
        {
            Vector3 c = ctx.Center;
            PlaceAt(ctx, c.x, c.z, 0.9f, 0.6f,
                p => MakeTable(ctx, p, 0f, 1.6f, 1.0f, 0.9f, _matMetalGrey, "PrepIsland"));
        }

        // Stacked crates in a corner.
        PlaceInCorner(ctx, 1, 0.5f, 0.5f, (pos, yaw) => MakeCrateStack(ctx, pos, "CrateStack"));
    }

    private static void FurnishLibrary(RoomContext ctx)
    {
        // Rows of tall bookshelves with wide aisles, running along Z.
        int budget = Mathf.Min(ctx.PropBudget(), 14);
        const float shelfLen = 2.4f, shelfDepth = 0.4f, aisle = 1.8f, colGap = aisle + shelfDepth;
        int col = 0;
        for (float x = ctx.MinX + 1.0f; x + shelfDepth * 0.5f <= ctx.MaxX - 0.5f && ctx.PropCount < budget; x += colGap, col++)
        {
            int row = 0;
            for (float z = ctx.MinZ + shelfLen * 0.5f + 0.3f; z + shelfLen * 0.5f <= ctx.MaxZ - 0.3f && ctx.PropCount < budget; z += shelfLen + 0.5f, row++)
            {
                // Shelves run long along Z (thin along X); MakeBookshelf builds its
                // length along local X, so yaw 90 maps that length onto world Z to
                // match the footprint validated above.
                PlaceAt(ctx, x, z, shelfDepth * 0.5f + 0.05f, shelfLen * 0.5f + 0.05f,
                    p => MakeBookshelf(ctx, p, 90f, shelfLen, $"Bookshelf_{col}_{row}"));
            }
        }

        // A couple of study tables with chairs near a wall, if there's room left.
        if (ctx.SizeX > 4f && ctx.SizeZ > 3f && ctx.PropCount < budget)
        {
            float x = ctx.MaxX - 1.2f;
            float z = ctx.Center.z;
            if (PlaceAt(ctx, x, z, 0.7f, 0.5f, p => MakeTable(ctx, p, 0f, 1.4f, 0.9f, 0.75f, _matWoodMid, "StudyTable")))
            {
                // Chair south of the table, facing the table (north, +Z).
                Vector3 cp = new Vector3(x, ctx.FloorY, z - 0.7f);
                if (ctx.Fits(cp.x, cp.z, 0.28f, 0.28f)) MakeChair(ctx, cp, 0f, "StudyChair");
            }
        }

        // A book cart in a corner.
        PlaceInCorner(ctx, 3, 0.4f, 0.3f, (pos, yaw) => MakeBookCart(ctx, pos, yaw, "BookCart"));
    }

    private static void FurnishGym(RoomContext ctx)
    {
        // Bleacher blocks along the longer wall.
        bool xLong = ctx.SizeX >= ctx.SizeZ;
        Wall bleacherWall = xLong ? Wall.North : Wall.East;
        MakeBleacher(ctx, bleacherWall, "Bleachers");

        // A locker bank along an adjacent wall.
        MakeLockerBankWall(ctx, xLong ? Wall.West : Wall.North, "LockerBank");

        // A couple of benches near the lockers. Reserve halfX 0.85 to cover the
        // full 1.6m bench length (corner yaw keeps the length on world X).
        PlaceInCorner(ctx, 0, 0.85f, 0.25f, (pos, yaw) => MakeBench(ctx, pos, yaw, 1.6f, "Bench0"));
        PlaceInCorner(ctx, 1, 0.85f, 0.25f, (pos, yaw) => MakeBench(ctx, pos, yaw, 1.6f, "Bench1"));

        // A few mats + cones scattered along the floor edges (small, low).
        int extras = Mathf.Min(4, Mathf.Max(2, ctx.PropBudget() / 3));
        for (int i = 0; i < extras; i++)
        {
            float x = Mathf.Lerp(ctx.MinX + 0.6f, ctx.MaxX - 0.6f, (float)ctx.Rng.NextDouble());
            float z = (i % 2 == 0) ? ctx.MinZ + 0.7f : ctx.MaxZ - 0.7f;
            if (i % 2 == 0)
                PlaceAt(ctx, x, z, 0.9f, 0.6f, p => MakeMat(ctx, p, "Mat" + i));
            else
                PlaceAt(ctx, x, z, 0.18f, 0.18f, p => MakeCone(ctx, p, "Cone" + i));
        }
    }

    private static void FurnishOffice(RoomContext ctx)
    {
        // Desk against the north wall, occupant seated on the wall side facing into
        // the room (principal-desk look).
        PlaceWallDesk(ctx, Wall.North, "Desk", "Chair", null);

        // Filing cabinets along a side wall.
        MakeFilingCabinets(ctx, Wall.West, "FilingCabinets");

        // A shelf in a corner.
        PlaceInCorner(ctx, 1, 1.0f, 0.4f, (pos, yaw) => MakeShelf(ctx, pos, yaw, "Shelf"));
    }

    private static void FurnishSecurity(RoomContext ctx)
    {
        // Desk against the north wall with two monitor boxes on the room-facing edge,
        // occupant on the wall side facing the monitors / into the room.
        PlaceWallDesk(ctx, Wall.North, "SecurityDesk", "Chair", deskCenter =>
        {
            Vector3 inward = InwardNormal(Wall.North);
            Vector3 along = new Vector3(inward.z, 0f, -inward.x); // perpendicular run axis
            Vector3 top = deskCenter + Vector3.up * 0.75f + inward * 0.12f;
            MakeMonitor(ctx, top - along * 0.3f, "Monitor0");
            MakeMonitor(ctx, top + along * 0.3f, "Monitor1");
        });

        MakeFilingCabinets(ctx, Wall.West, "FilingCabinets");
        PlaceInCorner(ctx, 1, 0.5f, 0.5f, (pos, yaw) => MakeLocker(ctx, pos, yaw, "Locker"));
    }

    /// <summary>
    /// Places a desk flush-ish against <paramref name="wall"/> with its occupant on
    /// the WALL side facing into the room, and a chair tucked between desk and wall.
    /// Optional <paramref name="onDesk"/> callback receives the desk's world centre
    /// (floor Y) to add desktop items. Facing is derived from the wall normal.
    /// </summary>
    private static void PlaceWallDesk(RoomContext ctx, Wall wall, string deskName, string chairName, System.Action<Vector3> onDesk)
    {
        WallInfo(ctx, wall, out float fx, out float fz, out bool alongX, out float inwardSign);
        Vector3 inward = InwardNormal(wall);
        float wallLine = alongX ? fz : fx;
        float yaw = YawFromDir(inward); // occupant faces into the room

        // Desk centre offset off the wall along the inward normal, leaving room for
        // the chair between desk and wall, centred on the run axis.
        const float deskOffset = 1.05f;
        float runCenter = alongX ? ctx.Center.x : ctx.Center.z;
        float normC = wallLine + inwardSign * deskOffset;
        float x = alongX ? runCenter : normC;
        float z = alongX ? normC : runCenter;

        // Footprint half-extents follow facing (desk 1.1 wide x 0.6 deep).
        float hX = alongX ? 0.6f : 0.4f;
        float hZ = alongX ? 0.4f : 0.6f;
        if (!PlaceAt(ctx, x, z, hX, hZ, p =>
            {
                MakeDesk(ctx, p, yaw, deskName);
                onDesk?.Invoke(p);
            }))
        {
            return;
        }

        // Chair on the wall side of the desk, facing into the room like the desk.
        Vector3 cp = new Vector3(x, ctx.FloorY, z) - inward * 0.7f;
        if (ctx.Fits(cp.x, cp.z, 0.28f, 0.28f)) MakeChair(ctx, cp, yaw, chairName);
    }

    private static void FurnishNurse(RoomContext ctx)
    {
        // 1-2 beds along a wall.
        int beds = (ctx.SizeZ > 4f) ? 2 : 1;
        float x = ctx.MinX + 1.0f;
        float startZ = ctx.MinZ + 1.2f;
        for (int i = 0; i < beds; i++)
        {
            float z = startZ + i * 2.4f;
            // Beds lie parallel to the wall (long axis on Z). MakeBed builds its
            // length along local Z already, so yaw 0 keeps it long on world Z.
            PlaceAt(ctx, x, z, 0.55f, 1.0f, p => MakeBed(ctx, p, 0f, $"Bed_{i}"));
        }

        // Medical cabinets / shelves on the opposite wall.
        MakeWallShelfRun(ctx, Wall.East, "MedCabinets");

        // A chair in a corner.
        PlaceInCorner(ctx, 3, 0.4f, 0.3f, (pos, yaw) => MakeChair(ctx, pos, yaw, "Chair"));
    }

    private static void FurnishStorage(RoomContext ctx, bool janitor)
    {
        // Shelving units along walls.
        MakeWallShelfRun(ctx, Wall.North, "ShelvesN");
        MakeWallShelfRun(ctx, Wall.West, "ShelvesW");

        // Stacked crates / boxes scattered around the perimeter.
        int budget = Mathf.Min(ctx.PropBudget(), 8);
        int placed = 0;
        for (int corner = 0; corner < 4 && placed < budget; corner++)
        {
            PlaceInCorner(ctx, corner, 0.5f, 0.5f, (pos, yaw) =>
            {
                if (ctx.Rng.NextDouble() > 0.5) MakeCrateStack(ctx, pos, $"CrateStack_{corner}");
                else MakeCrate(ctx, pos, 0.7f, $"Crate_{corner}");
            });
            placed++;
        }

        if (janitor)
        {
            // A mop bucket + a supply shelf.
            float x = ctx.Center.x;
            float z = ctx.MinZ + 0.7f;
            PlaceAt(ctx, x, z, 0.25f, 0.25f, p => MakeMopBucket(ctx, p, "MopBucket"));
            PlaceInCorner(ctx, 1, 0.4f, 0.35f, (pos, yaw) => MakeShelf(ctx, pos, yaw, "SupplyShelf"));
        }
    }

    private static void FurnishUtility(RoomContext ctx)
    {
        // Pipes along the walls (decorative, kept thin; colliders kept - they're obstacles).
        MakePipeRun(ctx, Wall.North, "PipesN");
        MakePipeRun(ctx, Wall.South, "PipesS");

        // A generator / machine box against a wall.
        float gx = ctx.MinX + 1.0f;
        float gz = ctx.Center.z;
        PlaceAt(ctx, gx, gz, 0.7f, 0.7f, p => MakeGenerator(ctx, p, 0f, "Generator"));

        // Crates, barrels, cable spools around the perimeter.
        int budget = Mathf.Min(ctx.PropBudget(), 10);
        for (int corner = 0; corner < 4 && ctx.PropCount < budget; corner++)
        {
            int kind = corner % 3;
            PlaceInCorner(ctx, corner, 0.5f, 0.5f, (pos, yaw) =>
            {
                switch (kind)
                {
                    case 0: MakeBarrel(ctx, pos, $"Barrel_{corner}"); break;
                    case 1: MakeCrate(ctx, pos, 0.7f, $"Crate_{corner}"); break;
                    default: MakeCableSpool(ctx, pos, $"Spool_{corner}"); break;
                }
            });
        }

        // A short scatter of barrels along the long axis edge.
        int barrels = Mathf.Min(3, Mathf.Max(1, budget / 3));
        for (int i = 0; i < barrels && ctx.PropCount < budget; i++)
        {
            float x = Mathf.Lerp(ctx.MinX + 0.6f, ctx.MaxX - 0.6f, (i + 0.5f) / barrels);
            float z = ctx.MaxZ - 0.6f;
            PlaceAt(ctx, x, z, 0.3f, 0.3f, p => MakeBarrel(ctx, p, $"EdgeBarrel_{i}"));
        }
    }

    private static void FurnishCourtyard(RoomContext ctx)
    {
        // Outdoor - keep light: a couple of benches + planter boxes around the
        // edges, a trash can. Do NOT crowd, so cap hard.
        int placed = 0;
        const int cap = 5;

        // Benches along two edges (halfX 0.85 covers the full 1.6m length).
        PlaceInCorner(ctx, 0, 0.85f, 0.25f, (pos, yaw) => { MakeBench(ctx, pos, yaw, 1.6f, "Bench0"); });
        placed++;
        if (placed < cap)
        {
            PlaceInCorner(ctx, 2, 0.85f, 0.25f, (pos, yaw) => { MakeBench(ctx, pos, yaw, 1.6f, "Bench1"); });
            placed++;
        }

        // Planter boxes in remaining corners.
        if (placed < cap)
        {
            PlaceInCorner(ctx, 1, 0.5f, 0.5f, (pos, yaw) => MakePlanter(ctx, pos, "Planter0"));
            placed++;
        }
        if (placed < cap)
        {
            PlaceInCorner(ctx, 3, 0.5f, 0.5f, (pos, yaw) => MakePlanter(ctx, pos, "Planter1"));
            placed++;
        }

        // A single trash can near an edge midpoint.
        if (placed < cap)
        {
            float x = ctx.Center.x;
            float z = ctx.MinZ + 0.6f;
            PlaceAt(ctx, x, z, 0.3f, 0.3f, p => MakeTrashCan(ctx, p, "TrashCan"));
        }
    }

    // === Placement helpers =================================================

    private enum Wall { North, South, East, West } // +Z, -Z, +X, -X

    /// <summary>
    /// Tries to place a prop centred at world (x,z) on the floor, validating the
    /// given half-footprint first. Returns true and invokes the builder if it fits.
    /// </summary>
    private static bool PlaceAt(RoomContext ctx, float x, float z, float halfX, float halfZ, System.Action<Vector3> build)
    {
        if (!ctx.Fits(x, z, halfX, halfZ)) return false;
        build(new Vector3(x, ctx.FloorY, z));
        return true;
    }

    /// <summary>
    /// Places a prop tucked into the given corner (0=SW,1=SE,2=NW,3=NE), inset by
    /// the prop's half extents so it sits against the walls without clipping.
    /// The yaw passed to the builder faces the prop's "back" toward the corner.
    /// </summary>
    private static void PlaceInCorner(RoomContext ctx, int corner, float halfX, float halfZ, System.Action<Vector3, float> build)
    {
        bool east = (corner == 1 || corner == 3);
        bool north = (corner == 2 || corner == 3);

        float x = east ? ctx.MaxX - halfX : ctx.MinX + halfX;
        float z = north ? ctx.MaxZ - halfZ : ctx.MinZ + halfZ;
        float yaw = north ? 180f : 0f;

        if (ctx.Fits(x, z, halfX, halfZ))
        {
            build(new Vector3(x, ctx.FloorY, z), yaw);
        }
    }

    /// <summary>
    /// Geometry of one wall in WORLD space. <paramref name="fixedX"/>/<paramref name="fixedZ"/>
    /// give the wall line; <paramref name="runsAlongX"/> is true for N/S walls
    /// (the run length lies on world X), false for E/W walls (run on world Z).
    /// <paramref name="inwardSign"/> is +1 or -1 along the wall NORMAL axis, pointing
    /// from the wall toward the room interior. Wall-run builders keep their roots
    /// UNROTATED and align geometry to world axes using these, so box shapes are
    /// never double-rotated.
    /// </summary>
    private static void WallInfo(RoomContext ctx, Wall wall, out float fixedX, out float fixedZ, out bool runsAlongX, out float inwardSign)
    {
        switch (wall)
        {
            case Wall.North: fixedX = 0f; fixedZ = ctx.MaxZ; runsAlongX = true; inwardSign = -1f; break; // interior is -Z
            case Wall.South: fixedX = 0f; fixedZ = ctx.MinZ; runsAlongX = true; inwardSign = +1f; break; // interior is +Z
            case Wall.East: fixedX = ctx.MaxX; fixedZ = 0f; runsAlongX = false; inwardSign = -1f; break; // interior is -X
            default: fixedX = ctx.MinX; fixedZ = 0f; runsAlongX = false; inwardSign = +1f; break;        // West, interior is +X
        }
    }

    // === Facing / orientation helpers ======================================
    //
    // FACING CONVENTION (used by every chair/desk/seat in this tool):
    //   A prop built by MakeDesk/MakeChair/etc. has its "front" (the side a person
    //   sits at, the back of a chair, the working edge of a desk) on local +Z.
    //   So a yaw of 0 makes the occupant FACE world +Z; +90 -> +X; 180 -> -Z;
    //   270 -> -X. YawFromDir converts any world direction into that yaw, so all
    //   facing is derived deterministically from room geometry (wall normals).

    /// <summary>Yaw (degrees) that makes a prop's local +Z point along <paramref name="dir"/> (world X/Z).</summary>
    private static float YawFromDir(Vector3 dir)
    {
        if (dir.sqrMagnitude < 1e-6f) return 0f;
        return Mathf.Atan2(dir.x, dir.z) * Mathf.Rad2Deg;
    }

    /// <summary>Unit world direction pointing from the wall INTO the room interior.</summary>
    private static Vector3 InwardNormal(Wall wall)
    {
        switch (wall)
        {
            case Wall.North: return new Vector3(0f, 0f, -1f);
            case Wall.South: return new Vector3(0f, 0f, 1f);
            case Wall.East: return new Vector3(-1f, 0f, 0f);
            default: return new Vector3(1f, 0f, 0f); // West
        }
    }

    /// <summary>
    /// Picks the classroom "front" (board/teacher) wall: the wall whose nearest
    /// doorway is FARTHEST away, so desks never face a door. Ties (e.g. no doorways
    /// at all) are broken toward the wall that gives the WIDER board / more columns
    /// of desks, then deterministically. Pure read of room geometry.
    /// </summary>
    private static Wall ChooseFrontWall(RoomContext ctx)
    {
        Wall[] walls = { Wall.North, Wall.South, Wall.East, Wall.West };
        Wall best = Wall.North;
        float bestScore = float.NegativeInfinity;

        foreach (Wall w in walls)
        {
            WallInfo(ctx, w, out float fx, out float fz, out bool alongX, out _);
            float wallLine = alongX ? fz : fx;

            // Nearest doorway, measured perpendicular to this wall line.
            float nearest = float.PositiveInfinity;
            foreach (Vector3 d in ctx.Doorways)
            {
                float perp = alongX ? Mathf.Abs(d.z - wallLine) : Mathf.Abs(d.x - wallLine);
                if (perp < nearest) nearest = perp;
            }
            if (float.IsPositiveInfinity(nearest)) nearest = 1000f; // no doorways on/near this wall

            // Prefer distance-from-doors first; small bonus for a wider board so the
            // teacher faces down the long axis when doors are equivalent.
            float wallWidth = alongX ? ctx.SizeX : ctx.SizeZ;
            float score = nearest * 10f + wallWidth;

            if (score > bestScore)
            {
                bestScore = score;
                best = w;
            }
        }
        return best;
    }

    /// <summary>World-aligned box scale for a wall-run piece: <paramref name="runLen"/>
    /// along the run axis, <paramref name="depth"/> along the wall-normal axis.</summary>
    private static Vector3 WallBoxScale(bool runsAlongX, float runLen, float height, float depth)
    {
        return runsAlongX ? new Vector3(runLen, height, depth) : new Vector3(depth, height, runLen);
    }

    /// <summary>World offset along the wall-normal axis (inward = positive distance).</summary>
    private static Vector3 NormalOffset(bool runsAlongX, float inwardSign, float distance)
    {
        return runsAlongX ? new Vector3(0f, 0f, inwardSign * distance) : new Vector3(inwardSign * distance, 0f, 0f);
    }

    /// <summary>World offset along the run axis.</summary>
    private static Vector3 RunOffset(bool runsAlongX, float distance)
    {
        return runsAlongX ? new Vector3(distance, 0f, 0f) : new Vector3(0f, 0f, distance);
    }

    // === Composite wall-run builders =======================================

    /// <summary>
    /// A run of counters along a wall. <paramref name="wallOffset"/> pushes the
    /// counter's BACK face this far off the wall line (into the room) so the player
    /// can walk behind it - used for cafeteria/kitchen service lines. 0 keeps it
    /// flush (the default for lab benches against the wall). If the room is too
    /// shallow for the requested offset it is reduced so the counter still fits.
    /// </summary>
    private static void MakeCounterRun(RoomContext ctx, Wall wall, string label, bool withSink, float wallOffset = 0f)
    {
        WallInfo(ctx, wall, out float fx, out float fz, out bool alongX, out float inward);
        const float depth = 0.6f, height = 0.9f, segLen = 1.2f;
        float runMin = alongX ? ctx.MinX : ctx.MinZ;
        float runMax = alongX ? ctx.MaxX : ctx.MaxZ;
        float wallLine = alongX ? fz : fx;

        // Clamp the walk-behind offset so the counter body still lands inside the
        // inset room rectangle on the wall-normal axis.
        float roomDepth = alongX ? ctx.SizeZ : ctx.SizeX;
        float maxOffset = Mathf.Max(0f, roomDepth - depth - 0.6f);
        float offset = Mathf.Clamp(wallOffset, 0f, maxOffset);

        int seg = 0;
        for (float t = runMin + segLen * 0.5f; t + segLen * 0.5f <= runMax; t += segLen, seg++)
        {
            // Body back face sits 'offset' off the wall, pushed inward by half its depth.
            float runC = t;
            float normC = wallLine + inward * (offset + depth * 0.5f);
            float x = alongX ? runC : normC;
            float z = alongX ? normC : runC;
            float hx = alongX ? segLen * 0.5f : depth * 0.5f;
            float hz = alongX ? depth * 0.5f : segLen * 0.5f;
            if (!ctx.Fits(x, z, hx, hz)) continue;

            Vector3 pos = new Vector3(x, ctx.FloorY, z);
            GameObject g = MakeRoot(ctx, $"{label}_{seg}", pos, 0f); // identity; world-aligned below
            AddBox(g.transform, "Body", _matMetalGrey, new Vector3(0f, height * 0.5f, 0f),
                WallBoxScale(alongX, segLen, height, depth), true);
            AddBox(g.transform, "Top", _matMetalDark, new Vector3(0f, height + 0.02f, 0f),
                WallBoxScale(alongX, segLen + 0.05f, 0.05f, depth + 0.05f), false);
            if (withSink && seg == 0)
            {
                AddBox(g.transform, "SinkBasin", _matMetalDark, new Vector3(0f, height - 0.08f, 0f),
                    new Vector3(0.4f, 0.16f, 0.4f), false);
            }
            ctx.Count();
        }
    }

    private static void MakeWallShelfRun(RoomContext ctx, Wall wall, string label)
    {
        WallInfo(ctx, wall, out float fx, out float fz, out bool alongX, out float inward);
        const float depth = 0.4f, segLen = 1.6f, height = 1.8f, board = 0.05f;
        float runMin = alongX ? ctx.MinX : ctx.MinZ;
        float runMax = alongX ? ctx.MaxX : ctx.MaxZ;
        float wallLine = alongX ? fz : fx;

        int seg = 0;
        for (float t = runMin + segLen * 0.5f; t + segLen * 0.5f <= runMax; t += segLen + 0.1f, seg++)
        {
            float normC = wallLine + inward * depth * 0.5f;
            float x = alongX ? t : normC;
            float z = alongX ? normC : t;
            float hx = alongX ? segLen * 0.5f : depth * 0.5f;
            float hz = alongX ? depth * 0.5f : segLen * 0.5f;
            if (!ctx.Fits(x, z, hx, hz)) continue;

            // World-aligned shelf unit (identity root): 2 uprights + 3 boards.
            GameObject g = MakeRoot(ctx, $"{label}_{seg}", new Vector3(x, ctx.FloorY, z), 0f);
            float halfRun = segLen * 0.5f - board * 0.5f;
            AddBox(g.transform, "Upright_A", _matWoodDark, RunOffset(alongX, -halfRun) + Vector3.up * (height * 0.5f),
                WallBoxScale(alongX, board, height, depth), true);
            AddBox(g.transform, "Upright_B", _matWoodDark, RunOffset(alongX, halfRun) + Vector3.up * (height * 0.5f),
                WallBoxScale(alongX, board, height, depth), true);
            for (int s = 0; s < 3; s++)
            {
                float y = Mathf.Lerp(0.1f, height - 0.1f, s / 2f);
                AddBox(g.transform, $"Board_{s}", _matWoodMid, Vector3.up * y,
                    WallBoxScale(alongX, segLen, board, depth), false);
            }
            ctx.Count();
        }
    }

    private static void MakePipeRun(RoomContext ctx, Wall wall, string label)
    {
        WallInfo(ctx, wall, out float fx, out float fz, out bool alongX, out float inward);
        float runMin = alongX ? ctx.MinX : ctx.MinZ;
        float runMax = alongX ? ctx.MaxX : ctx.MaxZ;
        float len = runMax - runMin;
        if (len < 1f) return;

        float t = (runMin + runMax) * 0.5f;
        const float depth = 0.2f;
        float wallLine = alongX ? fz : fx;
        float normC = wallLine + inward * depth;
        float x = alongX ? t : normC;
        float z = alongX ? normC : t;

        Vector3 pos = new Vector3(x, ctx.FloorY, z);
        GameObject g = MakeRoot(ctx, label, pos, 0f); // identity; pipes rotated to world axis
        // Two horizontal pipes at different heights, running along the wall axis.
        // A cylinder's long axis is local Y: rotate 90 about Z to lie along world X,
        // or 90 about X to lie along world Z.
        Quaternion lie = alongX ? Quaternion.Euler(0f, 0f, 90f) : Quaternion.Euler(90f, 0f, 0f);
        for (int i = 0; i < 2; i++)
        {
            float py = 1.1f + i * 0.6f;
            GameObject pipe = AddCylinder(g.transform, $"Pipe_{i}", _matRust,
                new Vector3(0f, py, 0f), new Vector3(0.12f, len * 0.45f, 0.12f), true);
            pipe.transform.localRotation = lie;
        }
        ctx.Count();
    }

    private static void MakeBleacher(RoomContext ctx, Wall wall, string label)
    {
        WallInfo(ctx, wall, out float fx, out float fz, out bool alongX, out float inward);
        float runMin = alongX ? ctx.MinX : ctx.MinZ;
        float runMax = alongX ? ctx.MaxX : ctx.MaxZ;
        float len = Mathf.Min(runMax - runMin - 1f, 8f);
        if (len < 2f) return;

        const int steps = 4;
        const float depthPerStep = 0.5f, heightPerStep = 0.4f;
        float totalDepth = steps * depthPerStep;
        float t = (runMin + runMax) * 0.5f;
        float wallLine = alongX ? fz : fx;
        // Centre the block so it sits against the wall, extending inward.
        float normC = wallLine + inward * totalDepth * 0.5f;
        float x = alongX ? t : normC;
        float z = alongX ? normC : t;

        float hx = alongX ? len * 0.5f : totalDepth * 0.5f;
        float hz = alongX ? totalDepth * 0.5f : len * 0.5f;
        if (!ctx.Fits(x, z, hx, hz)) return;

        Vector3 pos = new Vector3(x, ctx.FloorY, z);
        GameObject g = MakeRoot(ctx, label, pos, 0f); // identity; world-aligned risers
        for (int s = 0; s < steps; s++)
        {
            // Risers get taller toward the wall (outward = -inward from this centre).
            float along = -inward * (s - (steps - 1) * 0.5f) * depthPerStep;
            float h = (s + 1) * heightPerStep;
            AddBox(g.transform, $"Step_{s}", _matMetalGrey,
                NormalOffset(alongX, 1f, along) + Vector3.up * (h * 0.5f),
                WallBoxScale(alongX, len, h, depthPerStep), true);
        }
        ctx.Count();
    }

    private static void MakeLockerBankWall(RoomContext ctx, Wall wall, string label)
    {
        WallInfo(ctx, wall, out float fx, out float fz, out bool alongX, out float inward);
        const float lockerW = 0.45f, lockerH = 1.9f, depth = 0.45f;
        float runMin = alongX ? ctx.MinX : ctx.MinZ;
        float runMax = alongX ? ctx.MaxX : ctx.MaxZ;
        int count = Mathf.Clamp(Mathf.FloorToInt((runMax - runMin) / lockerW) - 1, 2, 8);
        float totalW = count * lockerW;

        float t = (runMin + runMax) * 0.5f;
        float wallLine = alongX ? fz : fx;
        float normC = wallLine + inward * depth * 0.5f;
        float x = alongX ? t : normC;
        float z = alongX ? normC : t;
        float hx = alongX ? totalW * 0.5f : depth * 0.5f;
        float hz = alongX ? depth * 0.5f : totalW * 0.5f;
        if (!ctx.Fits(x, z, hx, hz)) return;

        Vector3 pos = new Vector3(x, ctx.FloorY, z);
        GameObject g = MakeRoot(ctx, label, pos, 0f); // identity; world-aligned
        float start = -totalW * 0.5f + lockerW * 0.5f;
        for (int i = 0; i < count; i++)
        {
            AddBox(g.transform, $"Locker_{i}", _matMetalGrey,
                RunOffset(alongX, start + i * lockerW) + Vector3.up * (lockerH * 0.5f),
                WallBoxScale(alongX, lockerW * 0.95f, lockerH, depth), true);
        }
        ctx.Count();
    }

    private static void MakeFilingCabinets(RoomContext ctx, Wall wall, string label)
    {
        // World-aligned (identity root). Body width spans the run axis, depth the
        // wall normal; drawer faces sit on the inward side.
        WallInfo(ctx, wall, out float fx, out float fz, out bool alongX, out float inward);
        const float w = 0.5f, h = 1.3f, depth = 0.6f;
        float runMin = alongX ? ctx.MinX : ctx.MinZ;
        float runMax = alongX ? ctx.MaxX : ctx.MaxZ;
        float wallLine = alongX ? fz : fx;
        int count = Mathf.Clamp(Mathf.FloorToInt((runMax - runMin) / (w + 0.1f)), 1, 3);

        int placed = 0;
        float t = runMin + w * 0.5f + 0.3f;
        for (int i = 0; i < count; i++, t += w + 0.15f)
        {
            float normC = wallLine + inward * depth * 0.5f;
            float x = alongX ? t : normC;
            float z = alongX ? normC : t;
            float hx = alongX ? w * 0.5f : depth * 0.5f;
            float hz = alongX ? depth * 0.5f : w * 0.5f;
            if (!ctx.Fits(x, z, hx, hz)) continue;

            Vector3 pos = new Vector3(x, ctx.FloorY, z);
            GameObject g = MakeRoot(ctx, $"{label}_{i}", pos, 0f);
            AddBox(g.transform, "Body", _matMetalDark, new Vector3(0f, h * 0.5f, 0f),
                WallBoxScale(alongX, w, h, depth), true);
            for (int d = 0; d < 3; d++)
            {
                float dy = 0.25f + d * 0.4f;
                AddBox(g.transform, $"Drawer_{d}", _matMetalGrey,
                    NormalOffset(alongX, inward, depth * 0.5f + 0.02f) + Vector3.up * dy,
                    WallBoxScale(alongX, w * 0.85f, 0.3f, 0.04f), false);
            }
            placed++;
        }
        if (placed > 0) ctx.Count();
    }

    // === Single-prop builders ==============================================

    private static void MakeDesk(RoomContext ctx, Vector3 basePos, float yaw, string name)
    {
        const float w = 1.1f, d = 0.6f, top = 0.06f, height = 0.75f, leg = 0.06f;
        GameObject g = MakeRoot(ctx, name, basePos, yaw);
        AddBox(g.transform, "Top", _matWoodMid, new Vector3(0f, height - top * 0.5f, 0f), new Vector3(w, top, d), true);
        float lx = w * 0.5f - leg, lz = d * 0.5f - leg, ly = (height - top) * 0.5f;
        Vector3 ls = new Vector3(leg, height - top, leg);
        AddBox(g.transform, "Leg_FL", _matWoodDark, new Vector3(-lx, ly, lz), ls, true);
        AddBox(g.transform, "Leg_FR", _matWoodDark, new Vector3(lx, ly, lz), ls, true);
        AddBox(g.transform, "Leg_BL", _matWoodDark, new Vector3(-lx, ly, -lz), ls, true);
        AddBox(g.transform, "Leg_BR", _matWoodDark, new Vector3(lx, ly, -lz), ls, true);
        ctx.Count();
    }

    private static void MakeChair(RoomContext ctx, Vector3 basePos, float yaw, string name)
    {
        const float w = 0.42f, d = 0.42f, seatH = 0.45f, backH = 0.45f, leg = 0.05f, seatT = 0.05f;
        GameObject g = MakeRoot(ctx, name, basePos, yaw);
        AddBox(g.transform, "Seat", _matWoodMid, new Vector3(0f, seatH, 0f), new Vector3(w, seatT, d), true);
        AddBox(g.transform, "Back", _matWoodMid, new Vector3(0f, seatH + backH * 0.5f, -d * 0.5f + leg * 0.5f), new Vector3(w, backH, leg), true);
        float lx = w * 0.5f - leg, lz = d * 0.5f - leg;
        Vector3 ls = new Vector3(leg, seatH, leg);
        AddBox(g.transform, "Leg_FL", _matWoodDark, new Vector3(-lx, seatH * 0.5f, lz), ls, false);
        AddBox(g.transform, "Leg_FR", _matWoodDark, new Vector3(lx, seatH * 0.5f, lz), ls, false);
        AddBox(g.transform, "Leg_BL", _matWoodDark, new Vector3(-lx, seatH * 0.5f, -lz), ls, false);
        AddBox(g.transform, "Leg_BR", _matWoodDark, new Vector3(lx, seatH * 0.5f, -lz), ls, false);
        ctx.Count();
    }

    private static void MakeStool(RoomContext ctx, Vector3 basePos, string name)
    {
        const float r = 0.18f, seatH = 0.6f;
        GameObject g = MakeRoot(ctx, name, basePos, 0f);
        AddCylinder(g.transform, "Seat", _matMetalDark, new Vector3(0f, seatH, 0f), new Vector3(r * 2f, 0.03f, r * 2f), true);
        AddCylinder(g.transform, "Post", _matMetalGrey, new Vector3(0f, seatH * 0.5f, 0f), new Vector3(0.06f, seatH * 0.5f, 0.06f), false);
        ctx.Count();
    }

    private static void MakeTable(RoomContext ctx, Vector3 basePos, float yaw, float w, float d, float height, Material topMat, string name)
    {
        const float top = 0.06f, leg = 0.07f;
        GameObject g = MakeRoot(ctx, name, basePos, yaw);
        AddBox(g.transform, "Top", topMat, new Vector3(0f, height - top * 0.5f, 0f), new Vector3(w, top, d), true);
        float lx = w * 0.5f - leg, lz = d * 0.5f - leg, ly = (height - top) * 0.5f;
        Vector3 ls = new Vector3(leg, height - top, leg);
        AddBox(g.transform, "Leg_FL", _matWoodDark, new Vector3(-lx, ly, lz), ls, true);
        AddBox(g.transform, "Leg_FR", _matWoodDark, new Vector3(lx, ly, lz), ls, true);
        AddBox(g.transform, "Leg_BL", _matWoodDark, new Vector3(-lx, ly, -lz), ls, true);
        AddBox(g.transform, "Leg_BR", _matWoodDark, new Vector3(lx, ly, -lz), ls, true);
        ctx.Count();
    }

    private static void MakeShelf(RoomContext ctx, Vector3 basePos, float yaw, string name)
    {
        BuildShelfBody(ctx, basePos, yaw, 1.6f, name);
        ctx.Count();
    }

    /// <summary>Open shelf unit: 2 uprights + 3 boards. Used by MakeShelf and wall runs.</summary>
    private static void BuildShelfBody(RoomContext ctx, Vector3 basePos, float yaw, float width, string name)
    {
        const float height = 1.8f, depth = 0.35f, board = 0.05f;
        GameObject g = MakeRoot(ctx, name, basePos, yaw);
        float halfW = width * 0.5f - board * 0.5f;
        AddBox(g.transform, "Upright_L", _matWoodDark, new Vector3(-halfW, height * 0.5f, 0f), new Vector3(board, height, depth), true);
        AddBox(g.transform, "Upright_R", _matWoodDark, new Vector3(halfW, height * 0.5f, 0f), new Vector3(board, height, depth), true);
        for (int s = 0; s < 3; s++)
        {
            float y = Mathf.Lerp(0.1f, height - 0.1f, s / 2f);
            AddBox(g.transform, $"Board_{s}", _matWoodMid, new Vector3(0f, y, 0f), new Vector3(width, board, depth), false);
        }
    }

    private static void MakeBookshelf(RoomContext ctx, Vector3 basePos, float yaw, float length, string name)
    {
        const float height = 2.2f, depth = 0.4f, panel = 0.06f;
        GameObject g = MakeRoot(ctx, name, basePos, yaw);
        // Closed back + sides so it reads as a tall stack of books.
        AddBox(g.transform, "Back", _matWoodDark, new Vector3(0f, height * 0.5f, -depth * 0.5f + panel * 0.5f), new Vector3(length, height, panel), true);
        AddBox(g.transform, "Side_L", _matWoodDark, new Vector3(0f, height * 0.5f, 0f), new Vector3(panel, height, depth), false);
        // Shelves with "book" rows.
        for (int s = 0; s < 5; s++)
        {
            float y = 0.2f + s * (height - 0.4f) / 4f;
            AddBox(g.transform, $"Shelf_{s}", _matWoodMid, new Vector3(0f, y, 0f), new Vector3(length, 0.04f, depth), false);
            Material bookMat = (s % 2 == 0) ? _matFabricDark : _matWoodMid;
            AddBox(g.transform, $"Books_{s}", bookMat, new Vector3(0f, y + 0.16f, 0.02f), new Vector3(length * 0.92f, 0.28f, depth * 0.7f), false);
        }
        ctx.Count();
    }

    private static void MakeBookCart(RoomContext ctx, Vector3 basePos, float yaw, string name)
    {
        const float w = 0.8f, d = 0.4f, h = 0.9f;
        GameObject g = MakeRoot(ctx, name, basePos, yaw);
        AddBox(g.transform, "TopShelf", _matMetalGrey, new Vector3(0f, h, 0f), new Vector3(w, 0.04f, d), true);
        AddBox(g.transform, "MidShelf", _matMetalGrey, new Vector3(0f, h * 0.5f, 0f), new Vector3(w, 0.04f, d), false);
        AddBox(g.transform, "Books", _matFabricDark, new Vector3(0f, h + 0.14f, 0f), new Vector3(w * 0.8f, 0.24f, d * 0.7f), false);
        ctx.Count();
    }

    private static void MakeLocker(RoomContext ctx, Vector3 basePos, float yaw, string name)
    {
        const float w = 0.5f, h = 1.9f, d = 0.5f;
        GameObject g = MakeRoot(ctx, name, basePos, yaw);
        AddBox(g.transform, "Body", _matMetalGrey, new Vector3(0f, h * 0.5f, 0f), new Vector3(w, h, d), true);
        AddBox(g.transform, "Door", _matMetalDark, new Vector3(0f, h * 0.5f, d * 0.5f + 0.01f), new Vector3(w * 0.9f, h * 0.95f, 0.03f), false);
        ctx.Count();
    }

    private static void MakeCabinet(RoomContext ctx, Vector3 basePos, float yaw, string name)
    {
        const float w = 1.0f, h = 1.6f, d = 0.45f;
        GameObject g = MakeRoot(ctx, name, basePos, yaw);
        AddBox(g.transform, "Body", _matWoodDark, new Vector3(0f, h * 0.5f, 0f), new Vector3(w, h, d), true);
        AddBox(g.transform, "Door_L", _matWoodMid, new Vector3(-w * 0.25f, h * 0.5f, d * 0.5f + 0.01f), new Vector3(w * 0.45f, h * 0.92f, 0.03f), false);
        AddBox(g.transform, "Door_R", _matWoodMid, new Vector3(w * 0.25f, h * 0.5f, d * 0.5f + 0.01f), new Vector3(w * 0.45f, h * 0.92f, 0.03f), false);
        ctx.Count();
    }

    private static void MakeBed(RoomContext ctx, Vector3 basePos, float yaw, string name)
    {
        const float w = 0.9f, len = 1.9f, frameH = 0.45f, mattressT = 0.18f;
        GameObject g = MakeRoot(ctx, name, basePos, yaw);
        AddBox(g.transform, "Frame", _matMetalGrey, new Vector3(0f, frameH * 0.5f, 0f), new Vector3(w, frameH, len), true);
        AddBox(g.transform, "Mattress", _matFabricDark, new Vector3(0f, frameH + mattressT * 0.5f, 0f), new Vector3(w * 0.95f, mattressT, len * 0.97f), false);
        AddBox(g.transform, "Pillow", _matFabricDark, new Vector3(0f, frameH + mattressT + 0.04f, len * 0.5f - 0.3f), new Vector3(w * 0.6f, 0.1f, 0.4f), false);
        ctx.Count();
    }

    private static void MakeCrate(RoomContext ctx, Vector3 basePos, float size, string name)
    {
        GameObject g = MakeRoot(ctx, name, basePos, (float)(ctx.Rng.NextDouble() * 20.0 - 10.0));
        AddBox(g.transform, "Box", _matWoodMid, new Vector3(0f, size * 0.5f, 0f), new Vector3(size, size, size), true);
        ctx.Count();
    }

    private static void MakeCrateStack(RoomContext ctx, Vector3 basePos, string name)
    {
        GameObject g = MakeRoot(ctx, name, basePos, 0f);
        AddBox(g.transform, "Bottom", _matWoodMid, new Vector3(0f, 0.35f, 0f), new Vector3(0.7f, 0.7f, 0.7f), true);
        AddBox(g.transform, "Top", _matWoodDark, new Vector3(0.08f, 0.85f, 0.05f), new Vector3(0.5f, 0.5f, 0.5f), true);
        ctx.Count();
    }

    private static void MakeBarrel(RoomContext ctx, Vector3 basePos, string name)
    {
        const float r = 0.28f, h = 0.9f;
        GameObject g = MakeRoot(ctx, name, basePos, 0f);
        AddCylinder(g.transform, "Barrel", _matRust, new Vector3(0f, h * 0.5f, 0f), new Vector3(r * 2f, h * 0.5f, r * 2f), true);
        ctx.Count();
    }

    private static void MakeCableSpool(RoomContext ctx, Vector3 basePos, string name)
    {
        const float r = 0.4f, w = 0.5f;
        GameObject g = MakeRoot(ctx, name, basePos, 0f);
        // Spool lying on its side: a wide short cylinder rotated to roll axis = X.
        GameObject spool = AddCylinder(g.transform, "Spool", _matWoodDark, new Vector3(0f, r, 0f), new Vector3(r * 2f, w * 0.5f, r * 2f), true);
        spool.transform.localRotation = Quaternion.Euler(0f, 0f, 90f);
        ctx.Count();
    }

    private static void MakeGenerator(RoomContext ctx, Vector3 basePos, float yaw, string name)
    {
        GameObject g = MakeRoot(ctx, name, basePos, yaw);
        AddBox(g.transform, "Body", _matMetalDark, new Vector3(0f, 0.6f, 0f), new Vector3(1.2f, 1.2f, 1.0f), true);
        AddBox(g.transform, "Vent", _matMetalGrey, new Vector3(0f, 0.6f, 0.5f + 0.01f), new Vector3(0.8f, 0.5f, 0.05f), false);
        AddCylinder(g.transform, "Exhaust", _matRust, new Vector3(0.45f, 1.4f, -0.3f), new Vector3(0.12f, 0.35f, 0.12f), false);
        ctx.Count();
    }

    private static void MakePipe(RoomContext ctx, Vector3 basePos, string name)
    {
        // Standalone vertical pipe (kept for the builder roster; wall runs use MakePipeRun).
        const float h = 2.0f;
        GameObject g = MakeRoot(ctx, name, basePos, 0f);
        AddCylinder(g.transform, "Pipe", _matRust, new Vector3(0f, h * 0.5f, 0f), new Vector3(0.16f, h * 0.5f, 0.16f), true);
        ctx.Count();
    }

    private static void MakeBench(RoomContext ctx, Vector3 basePos, float yaw, float length, string name)
    {
        const float seatH = 0.45f, seatD = 0.35f, seatT = 0.06f, leg = 0.06f;
        GameObject g = MakeRoot(ctx, name, basePos, yaw);
        AddBox(g.transform, "Seat", _matWoodMid, new Vector3(0f, seatH, 0f), new Vector3(length, seatT, seatD), true);
        float lx = length * 0.5f - leg, lz = seatD * 0.5f - leg;
        Vector3 ls = new Vector3(leg, seatH, leg);
        AddBox(g.transform, "Leg_FL", _matWoodDark, new Vector3(-lx, seatH * 0.5f, lz), ls, false);
        AddBox(g.transform, "Leg_FR", _matWoodDark, new Vector3(lx, seatH * 0.5f, lz), ls, false);
        AddBox(g.transform, "Leg_BL", _matWoodDark, new Vector3(-lx, seatH * 0.5f, -lz), ls, false);
        AddBox(g.transform, "Leg_BR", _matWoodDark, new Vector3(lx, seatH * 0.5f, -lz), ls, false);
        ctx.Count();
    }

    private static void MakeWhiteboard(RoomContext ctx, Wall wall, string name)
    {
        WallInfo(ctx, wall, out float fx, out float fz, out bool alongX, out float inward);
        const float w = 2.2f, h = 1.2f, thick = 0.04f;
        // Centred on the wall at eye-ish height, sitting just off the wall face (inward).
        float wallLine = alongX ? fz : fx;
        float normC = wallLine + inward * thick;
        float x = alongX ? ctx.Center.x : normC;
        float z = alongX ? normC : ctx.Center.z;
        Vector3 pos = new Vector3(x, ctx.FloorY + 1.4f, z);

        GameObject g = MakeRoot(ctx, name, pos, 0f); // identity; world-aligned panel
        // Decorative panel - NO collider (flat wall decoration).
        AddBox(g.transform, "Panel", _matWhiteboard, Vector3.zero,
            WallBoxScale(alongX, w, h, thick), false);
        AddBox(g.transform, "Frame", _matMetalGrey, Vector3.zero,
            WallBoxScale(alongX, w + 0.08f, h + 0.08f, thick * 0.5f), false);
        ctx.Count();
    }

    private static void MakeTrashCan(RoomContext ctx, Vector3 basePos, string name)
    {
        const float r = 0.22f, h = 0.6f;
        GameObject g = MakeRoot(ctx, name, basePos, 0f);
        AddCylinder(g.transform, "Can", _matPlasticDark, new Vector3(0f, h * 0.5f, 0f), new Vector3(r * 2f, h * 0.5f, r * 2f), true);
        ctx.Count();
    }

    private static void MakeMopBucket(RoomContext ctx, Vector3 basePos, string name)
    {
        GameObject g = MakeRoot(ctx, name, basePos, 0f);
        AddBox(g.transform, "Bucket", _matPlasticDark, new Vector3(0f, 0.2f, 0f), new Vector3(0.45f, 0.4f, 0.35f), true);
        // Mop handle leaning out of the bucket.
        GameObject handle = AddCylinder(g.transform, "Handle", _matWoodDark, new Vector3(0.1f, 0.8f, 0f), new Vector3(0.05f, 0.6f, 0.05f), false);
        handle.transform.localRotation = Quaternion.Euler(0f, 0f, 18f);
        ctx.Count();
    }

    private static void MakeMonitor(RoomContext ctx, Vector3 worldCenter, string name)
    {
        // Sits ON the desktop (caller passes desk-top Y). Small box "screen".
        GameObject g = MakeRoot(ctx, name, worldCenter, 0f);
        AddBox(g.transform, "Screen", _matGlassDark, new Vector3(0f, 0.18f, 0f), new Vector3(0.4f, 0.3f, 0.05f), false);
        AddBox(g.transform, "Stand", _matMetalDark, new Vector3(0f, 0.03f, 0f), new Vector3(0.12f, 0.06f, 0.12f), false);
        ctx.Count();
    }

    private static void MakeMat(RoomContext ctx, Vector3 basePos, string name)
    {
        GameObject g = MakeRoot(ctx, name, basePos, 0f);
        // Flat floor mat - keep a thin collider (it's a low obstacle the player can step over visually, but harmless).
        AddBox(g.transform, "Mat", _matFabricDark, new Vector3(0f, 0.03f, 0f), new Vector3(1.6f, 0.06f, 1.1f), false);
        ctx.Count();
    }

    private static void MakeCone(RoomContext ctx, Vector3 basePos, string name)
    {
        GameObject g = MakeRoot(ctx, name, basePos, 0f);
        AddCylinder(g.transform, "Cone", _matRust, new Vector3(0f, 0.18f, 0f), new Vector3(0.28f, 0.18f, 0.28f), false);
        ctx.Count();
    }

    private static void MakePlanter(RoomContext ctx, Vector3 basePos, string name)
    {
        GameObject g = MakeRoot(ctx, name, basePos, 0f);
        AddBox(g.transform, "Box", _matConcrete, new Vector3(0f, 0.25f, 0f), new Vector3(0.8f, 0.5f, 0.8f), true);
        AddBox(g.transform, "Soil", _matWoodDark, new Vector3(0f, 0.5f, 0f), new Vector3(0.7f, 0.06f, 0.7f), false);
        ctx.Count();
    }

    // === Low-level primitive helpers =======================================

    /// <summary>
    /// Creates an empty prop root parented under the room container, positioned at
    /// the given world point. For floor-standing props the caller passes a base
    /// point carrying ctx.FloorY and builds children upward from local Y=0; for a
    /// surface-mounted item (e.g. a monitor) the caller passes the explicit world
    /// centre instead.
    /// </summary>
    private static GameObject MakeRoot(RoomContext ctx, string name, Vector3 basePos, float yaw)
    {
        GameObject g = new GameObject(name);
        g.transform.SetParent(ctx.Parent, false);
        g.transform.position = basePos;
        g.transform.rotation = Quaternion.Euler(0f, yaw, 0f);
        g.transform.localScale = Vector3.one; // parent (room container) is unscaled
        return g;
    }

    private static GameObject AddBox(Transform parent, string name, Material mat, Vector3 localPos, Vector3 localScale, bool keepCollider)
    {
        GameObject box = GameObject.CreatePrimitive(PrimitiveType.Cube);
        box.name = name;
        box.transform.SetParent(parent, false);
        box.transform.localPosition = localPos;
        box.transform.localRotation = Quaternion.identity;
        box.transform.localScale = localScale;
        FinishPrimitive(box, mat, keepCollider);
        return box;
    }

    private static GameObject AddCylinder(Transform parent, string name, Material mat, Vector3 localPos, Vector3 localScale, bool keepCollider)
    {
        GameObject cyl = GameObject.CreatePrimitive(PrimitiveType.Cylinder);
        cyl.name = name;
        cyl.transform.SetParent(parent, false);
        cyl.transform.localPosition = localPos;
        cyl.transform.localRotation = Quaternion.identity;
        cyl.transform.localScale = localScale;
        FinishPrimitive(cyl, mat, keepCollider);
        return cyl;
    }

    private static void FinishPrimitive(GameObject go, Material mat, bool keepCollider)
    {
        if (!keepCollider)
        {
            Collider col = go.GetComponent<Collider>();
            if (col != null) Object.DestroyImmediate(col);
        }

        MeshRenderer mr = go.GetComponent<MeshRenderer>();
        if (mr != null) mr.sharedMaterial = mat;
        go.isStatic = true;
    }

    // === Scene lookup helpers ==============================================

    private static MeshRenderer FindFloor(List<MeshRenderer> renderers, string roomId)
    {
        string target = roomId + "_Floor";
        foreach (MeshRenderer r in renderers)
        {
            if (r.gameObject.name == target) return r;
        }
        return null;
    }

    /// <summary>
    /// Collects the world positions of THIS room's own doorway transoms. A room's
    /// transoms are named "&lt;roomid&gt;_&lt;N|S|E|W&gt;_Seg#_..._Transom"; matching on the
    /// direction token immediately after the id avoids grabbing sub-rooms (e.g.
    /// "library" must not pick up "library_basement_*"). "AntiZFightCover" variants
    /// are ignored, and generated-door transoms (prefixed "Door_") never match.
    /// </summary>
    private static List<Vector3> CollectDoorways(List<MeshRenderer> renderers, string roomId)
    {
        List<Vector3> result = new List<Vector3>();
        string[] prefixes =
        {
            roomId + "_N_", roomId + "_S_", roomId + "_E_", roomId + "_W_",
        };

        foreach (MeshRenderer r in renderers)
        {
            string n = r.gameObject.name;
            if (!n.Contains("Transom")) continue;
            if (n.Contains("AntiZFightCover")) continue;

            bool mine = false;
            foreach (string p in prefixes)
            {
                if (n.StartsWith(p)) { mine = true; break; }
            }
            if (!mine) continue;

            result.Add(r.bounds.center);
        }
        return result;
    }

    private static bool IsGeneratedRoot(string rootName)
    {
        foreach (string g in GeneratedRootNames)
        {
            if (rootName == g) return true;
        }
        return false;
    }

    private static GameObject RecreateRoot()
    {
        GameObject existing = GameObject.Find(RootName);
        if (existing != null) Object.DestroyImmediate(existing);

        GameObject root = new GameObject(RootName);
        root.transform.position = Vector3.zero;
        root.transform.rotation = Quaternion.identity;
        root.transform.localScale = Vector3.one;
        return root;
    }

    // === Materials =========================================================

    private static void BuildMaterials()
    {
        _matWoodDark = CreateMaterial("Furniture - Wood Dark", new Color(0.20f, 0.14f, 0.09f), 0.15f);
        _matWoodMid = CreateMaterial("Furniture - Wood Mid", new Color(0.34f, 0.24f, 0.15f), 0.18f);
        _matMetalGrey = CreateMaterial("Furniture - Metal Grey", new Color(0.34f, 0.37f, 0.40f), 0.45f);
        _matMetalDark = CreateMaterial("Furniture - Metal Dark", new Color(0.20f, 0.22f, 0.24f), 0.40f);
        _matWhiteboard = CreateMaterial("Furniture - Whiteboard", new Color(0.62f, 0.64f, 0.63f), 0.30f);
        _matFabricDark = CreateMaterial("Furniture - Fabric Dark", new Color(0.18f, 0.19f, 0.22f), 0.05f);
        _matPlasticDark = CreateMaterial("Furniture - Plastic Dark", new Color(0.12f, 0.13f, 0.14f), 0.25f);
        _matConcrete = CreateMaterial("Furniture - Concrete", new Color(0.30f, 0.30f, 0.29f), 0.10f);
        _matRust = CreateMaterial("Furniture - Rust Metal", new Color(0.32f, 0.20f, 0.13f), 0.20f);
        _matGlassDark = CreateMaterial("Furniture - Glass Dark", new Color(0.06f, 0.07f, 0.09f), 0.70f);
    }

    private static Material CreateMaterial(string materialName, Color color, float smoothness)
    {
        string path = $"{MaterialFolder}/{materialName}.mat";
        Material mat = AssetDatabase.LoadAssetAtPath<Material>(path);
        if (mat == null)
        {
            Shader shader = Shader.Find("Universal Render Pipeline/Lit");
            if (shader == null) shader = Shader.Find("Standard");
            mat = new Material(shader) { name = materialName };
            AssetDatabase.CreateAsset(mat, path);
        }

        if (mat.HasProperty("_BaseColor")) mat.SetColor("_BaseColor", color);
        if (mat.HasProperty("_Color")) mat.SetColor("_Color", color);
        if (mat.HasProperty("_Smoothness")) mat.SetFloat("_Smoothness", smoothness);
        if (mat.HasProperty("_Metallic")) mat.SetFloat("_Metallic", 0f);

        EditorUtility.SetDirty(mat);
        return mat;
    }

    private static void EnsureFolder(string folderPath)
    {
        if (AssetDatabase.IsValidFolder(folderPath)) return;

        string parent = System.IO.Path.GetDirectoryName(folderPath)?.Replace("\\", "/");
        string leaf = System.IO.Path.GetFileName(folderPath);
        if (!string.IsNullOrEmpty(parent) && !AssetDatabase.IsValidFolder(parent))
        {
            EnsureFolder(parent);
        }
        AssetDatabase.CreateFolder(parent, leaf);
    }

    /// <summary>Stable hash of a string (avoids platform-dependent string.GetHashCode).</summary>
    private static int StableHash(string s)
    {
        unchecked
        {
            int hash = 17;
            foreach (char c in s) hash = hash * 31 + c;
            return hash;
        }
    }
}
